name: SARS-CoV-2-RBD_DMS
channels:
  - bioconda
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.7
  - pip
  - pbccs
  - raxml
  - sra-tools
  - dssp
  - minimap2
  - node-js
  - mafft
  - pip:
    - alignparse
    - dms-variants
    - jupyter
    - jupyterlab
    - jupyter_contrib_nbextensions
    - snakemake
