name: SARS-CoV-2-RBD_DMS
channels:
  - bioconda
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.7
  - pip
  - pbccs
  - raxml
  - sra-tools
  - dssp
  - minimap2
  - nodejs
  - mafft
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - snakemake
  - altair
  - git-lfs
  - pip:
    - alignparse
    - dms-variants
    - logomaker
    - natsort
